#!/bin/sh
export PERL5LIB=$PERL5LIB:/kb/deployment/lib
export KB_DEPLOYMENT_CONFIG=/kb/deployment/deployment.cfg
export KB_SERVICE_NAME=KBaseExpression
export STARMAN_DEBUG=1
/kb/runtime/bin/starman --listen :7075 --workers 1 \
    /kb/deployment/lib/KBaseExpression.psgi
