#!/bin/sh
echo trying to stop KBaseExpression service.
pid_file=/kb/deployment/services/KBaseExpression/service.pid
if [ ! -f $pid_file ] ; then 
	echo "No pid file: $pid_file found for service KBaseExpression."
	exit 1
fi
pid=$(cat $pid_file)
kill $pid
