#!/bin/sh
echo trying to stop trees service.
pid_file=/kb/deployment/services/trees/service.pid
if [ ! -f $pid_file ] ; then 
    echo "No pid file: $pid_file found for service KBaseTrees."
    exit 1
fi
pid=$(cat $pid_file)
kill $pid
