############################################################
#
# Autogenerated by the KBase type compiler -
# any changes made here will be overwritten
#
############################################################

try:
    import json as _json
except ImportError:
    import sys
    sys.path.append('simplejson-2.3.3')
    import simplejson as _json

import requests as _requests
import urlparse as _urlparse
import random as _random
import base64 as _base64
from ConfigParser import ConfigParser as _ConfigParser
import os as _os

_CT = 'content-type'
_AJ = 'application/json'
_URL_SCHEME = frozenset(['http', 'https'])


def _get_token(user_id, password,
               auth_svc='https://nexus.api.globusonline.org/goauth/token?' +
                        'grant_type=client_credentials'):
    # This is bandaid helper function until we get a full
    # KBase python auth client released
    auth = _base64.encodestring(user_id + ':' + password)
    headers = {'Authorization': 'Basic ' + auth}
    ret = _requests.get(auth_svc, headers=headers, allow_redirects=True)
    status = ret.status_code
    if status >= 200 and status <= 299:
        tok = _json.loads(ret.text)
    elif status == 403:
        raise Exception('Authentication failed: Bad user_id/password ' +
                        'combination for user %s' % (user_id))
    else:
        raise Exception(ret.text)
    return tok['access_token']


def _read_rcfile(file=_os.environ['HOME'] + '/.authrc'):  # @ReservedAssignment
    # Another bandaid to read in the ~/.authrc file if one is present
    authdata = None
    if _os.path.exists(file):
        try:
            with open(file) as authrc:
                rawdata = _json.load(authrc)
                # strip down whatever we read to only what is legit
                authdata = {x: rawdata.get(x) for x in (
                    'user_id', 'token', 'client_secret', 'keyfile',
                    'keyfile_passphrase', 'password')}
        except Exception, e:
            print "Error while reading authrc file %s: %s" % (file, e)
    return authdata


def _read_inifile(file=_os.environ.get(  # @ReservedAssignment
                  'KB_DEPLOYMENT_CONFIG', _os.environ['HOME'] +
                  '/.kbase_config')):
    # Another bandaid to read in the ~/.kbase_config file if one is present
    authdata = None
    if _os.path.exists(file):
        try:
            config = _ConfigParser()
            config.read(file)
            # strip down whatever we read to only what is legit
            authdata = {x: config.get('authentication', x)
                        if config.has_option('authentication', x)
                        else None for x in ('user_id', 'token',
                                            'client_secret', 'keyfile',
                                            'keyfile_passphrase', 'password')}
        except Exception, e:
            print "Error while reading INI file %s: %s" % (file, e)
    return authdata


class ServerError(Exception):

    def __init__(self, name, code, message, data=None, error=None):
        self.name = name
        self.code = code
        self.message = '' if message is None else message
        self.data = data or error or ''
        # data = JSON RPC 2.0, error = 1.1

    def __str__(self):
        return self.name + ': ' + str(self.code) + '. ' + self.message + \
            '\n' + self.data


class _JSONObjectEncoder(_json.JSONEncoder):

    def default(self, obj):
        if isinstance(obj, set):
            return list(obj)
        if isinstance(obj, frozenset):
            return list(obj)
        return _json.JSONEncoder.default(self, obj)


class KBaseTrees(object):

    def __init__(self, url=None, timeout=30 * 60, user_id=None,
                 password=None, token=None, ignore_authrc=False,
                 trust_all_ssl_certificates=False):
        if url is None:
            url = 'https://kbase.us/services/trees'
        scheme, _, _, _, _, _ = _urlparse.urlparse(url)
        if scheme not in _URL_SCHEME:
            raise ValueError(url + " isn't a valid http url")
        self.url = url
        self.timeout = int(timeout)
        self._headers = dict()
        self.trust_all_ssl_certificates = trust_all_ssl_certificates
        # token overrides user_id and password
        if token is not None:
            self._headers['AUTHORIZATION'] = token
        elif user_id is not None and password is not None:
            self._headers['AUTHORIZATION'] = _get_token(user_id, password)
        elif 'KB_AUTH_TOKEN' in _os.environ:
            self._headers['AUTHORIZATION'] = _os.environ.get('KB_AUTH_TOKEN')
        elif not ignore_authrc:
            authdata = _read_inifile()
            if authdata is None:
                authdata = _read_rcfile()
            if authdata is not None:
                if authdata.get('token') is not None:
                    self._headers['AUTHORIZATION'] = authdata['token']
                elif(authdata.get('user_id') is not None
                     and authdata.get('password') is not None):
                    self._headers['AUTHORIZATION'] = _get_token(
                        authdata['user_id'], authdata['password'])
        if self.timeout < 1:
            raise ValueError('Timeout value must be at least 1 second')

    def _call(self, method, params):
        arg_hash = {'method': method,
                    'params': params,
                    'version': '1.1',
                    'id': str(_random.random())[2:]
                    }

        body = _json.dumps(arg_hash, cls=_JSONObjectEncoder)
        ret = _requests.post(self.url, data=body, headers=self._headers,
                             timeout=self.timeout,
                             verify=not self.trust_all_ssl_certificates)
        if ret.status_code == _requests.codes.server_error:
            if _CT in ret.headers and ret.headers[_CT] == _AJ:
                err = _json.loads(ret.text)
                if 'error' in err:
                    raise ServerError(**err['error'])
                else:
                    raise ServerError('Unknown', 0, ret.text)
            else:
                raise ServerError('Unknown', 0, ret.text)
        if ret.status_code != _requests.codes.OK:
            ret.raise_for_status()
        resp = _json.loads(ret.text)
        if 'result' not in resp:
            raise ServerError('Unknown', 0, 'An unknown server error occurred')
        return resp['result']

    def replace_node_names(self, tree, replacements):
        resp = self._call('KBaseTrees.replace_node_names',
                          [tree, replacements])
        return resp[0]

    def remove_node_names_and_simplify(self, tree, removal_list):
        resp = self._call('KBaseTrees.remove_node_names_and_simplify',
                          [tree, removal_list])
        return resp[0]

    def merge_zero_distance_leaves(self, tree):
        resp = self._call('KBaseTrees.merge_zero_distance_leaves',
                          [tree])
        return resp[0]

    def extract_leaf_node_names(self, tree):
        resp = self._call('KBaseTrees.extract_leaf_node_names',
                          [tree])
        return resp[0]

    def extract_node_names(self, tree):
        resp = self._call('KBaseTrees.extract_node_names',
                          [tree])
        return resp[0]

    def get_node_count(self, tree):
        resp = self._call('KBaseTrees.get_node_count',
                          [tree])
        return resp[0]

    def get_leaf_count(self, tree):
        resp = self._call('KBaseTrees.get_leaf_count',
                          [tree])
        return resp[0]

    def get_tree(self, tree_id, options):
        resp = self._call('KBaseTrees.get_tree',
                          [tree_id, options])
        return resp[0]

    def get_alignment(self, alignment_id, options):
        resp = self._call('KBaseTrees.get_alignment',
                          [alignment_id, options])
        return resp[0]

    def get_tree_data(self, tree_ids):
        resp = self._call('KBaseTrees.get_tree_data',
                          [tree_ids])
        return resp[0]

    def get_alignment_data(self, alignment_ids):
        resp = self._call('KBaseTrees.get_alignment_data',
                          [alignment_ids])
        return resp[0]

    def get_tree_ids_by_feature(self, feature_ids):
        resp = self._call('KBaseTrees.get_tree_ids_by_feature',
                          [feature_ids])
        return resp[0]

    def get_tree_ids_by_protein_sequence(self, protein_sequence_ids):
        resp = self._call('KBaseTrees.get_tree_ids_by_protein_sequence',
                          [protein_sequence_ids])
        return resp[0]

    def get_alignment_ids_by_feature(self, feature_ids):
        resp = self._call('KBaseTrees.get_alignment_ids_by_feature',
                          [feature_ids])
        return resp[0]

    def get_alignment_ids_by_protein_sequence(self, protein_sequence_ids):
        resp = self._call('KBaseTrees.get_alignment_ids_by_protein_sequence',
                          [protein_sequence_ids])
        return resp[0]

    def get_tree_ids_by_source_id_pattern(self, pattern):
        resp = self._call('KBaseTrees.get_tree_ids_by_source_id_pattern',
                          [pattern])
        return resp[0]

    def get_leaf_to_protein_map(self, tree_id):
        resp = self._call('KBaseTrees.get_leaf_to_protein_map',
                          [tree_id])
        return resp[0]

    def get_leaf_to_feature_map(self, tree_id):
        resp = self._call('KBaseTrees.get_leaf_to_feature_map',
                          [tree_id])
        return resp[0]

    def import_tree_from_cds(self, selection, targetWsNameOrId):
        resp = self._call('KBaseTrees.import_tree_from_cds',
                          [selection, targetWsNameOrId])
        return resp[0]

    def compute_abundance_profile(self, abundance_params):
        resp = self._call('KBaseTrees.compute_abundance_profile',
                          [abundance_params])
        return resp[0]

    def filter_abundance_profile(self, abundance_data, filter_params):
        resp = self._call('KBaseTrees.filter_abundance_profile',
                          [abundance_data, filter_params])
        return resp[0]

    def draw_html_tree(self, tree, display_options):
        resp = self._call('KBaseTrees.draw_html_tree',
                          [tree, display_options])
        return resp[0]

    def construct_species_tree(self, input):
        resp = self._call('KBaseTrees.construct_species_tree',
                          [input])
        return resp[0]

    def construct_multiple_alignment(self, params):
        resp = self._call('KBaseTrees.construct_multiple_alignment',
                          [params])
        return resp[0]

    def construct_tree_for_alignment(self, params):
        resp = self._call('KBaseTrees.construct_tree_for_alignment',
                          [params])
        return resp[0]

    def find_close_genomes(self, params):
        resp = self._call('KBaseTrees.find_close_genomes',
                          [params])
        return resp[0]

    def guess_taxonomy_path(self, params):
        resp = self._call('KBaseTrees.guess_taxonomy_path',
                          [params])
        return resp[0]

    def build_genome_set_from_tree(self, params):
        resp = self._call('KBaseTrees.build_genome_set_from_tree',
                          [params])
        return resp[0]
