#!/bin/sh
export KB_TOP=/kb/deployment
export KB_DEPLOYMENT_CONFIG=$KB_TOP/deployment.cfg
export KB_RUNTIME=/kb/runtime
export PATH=$KB_TOP/bin:$KB_RUNTIME/bin:$PATH
export PERL5LIB=$KB_TOP/lib:$KB_TOP/lib/perl5:$KB_TOP/lib/perl5/site_perl/5.16.1
export KB_SERVICE_NAME=fbaModelServices
export KB_SERVICE_DIR=$KB_TOP/services/fbaModelServices
export MODELSEED_CONF=$KB_SERVICE_DIR/config.json

kb_service_psgi=lib/fbaModelServices.psgi
pid_file=$KB_SERVICE_DIR/service.pid

exec $KB_RUNTIME/bin/starman --listen :7036  $KB_TOP/$kb_service_psgi   
