#!/bin/sh
export KB_TOP=/kb/deployment
export KB_DEPLOYMENT_CONFIG=$KB_TOP/deployment.cfg
export KB_RUNTIME=/kb/runtime
export PATH=$KB_TOP/bin:$KB_RUNTIME/bin:$PATH
export PERL5LIB=$KB_TOP/lib
export KB_SERVICE_NAME=CoExpression
export KB_SERVICE_DIR=$KB_TOP/services/CoExpression

pid_file=$KB_SERVICE_DIR/service.pid

exec $KB_RUNTIME/bin/starman --listen :7063  $KB_TOP/lib/CoExpression.psgi \
   --access-log $KB_SERVICE_DIR/access.log  
