#!/bin/sh
export KB_TOP=/kb/deployment
export KB_RUNTIME=/kb/runtime
export PATH=$KB_TOP/bin:$KB_RUNTIME/bin:$PATH
export PERL5LIB=$KB_TOP/lib
export KB_SERVICE_DIR=$KB_TOP/services/cdmi_api
export KB_SPHINX_PORT=7038
export KB_SPHINX_HOST=localhost
export CDMIDBD=$KB_TOP/lib/KSaplingDBD.xml
export KB_DEPLOYMENT_CONFIG=$KB_TOP/deployment.cfg
export KB_SERVICE_NAME=cdmi_api

pid_file=$KB_SERVICE_DIR/service.pid

workers="--workers 8"
max_requests="--max-requests 100"

starman_params="--listen :7032  $workers $max_requests"

starman_params="$starman_params "
starman_params="$starman_params --access-log $KB_SERVICE_DIR/access.log"

starman_params="$starman_params "

exec $KB_RUNTIME/bin/perl $KB_RUNTIME/bin/starman $starman_params $KB_TOP/lib/CDMI.psgi

