#!/bin/sh
export KB_TOP=/kb/deployment
export KB_RUNTIME=/kb/runtime
export PATH=$KB_TOP/bin:$KB_RUNTIME/bin:$PATH
export PERL5LIB=$KB_TOP/lib
export KB_SERVICE_DIR=$KB_TOP/services/narrative_job_service
export KB_DEPLOYMENT_CONFIG=$KB_TOP/deployment.cfg

PID_FILE=$KB_SERVICE_DIR/service.pid

$KB_RUNTIME/bin/perl $KB_RUNTIME/bin/starman --listen :7080  $KB_TOP/lib/NarrativeJobService.psgi  --workers 20 
