#!/bin/sh

export KB_SERVICE_NAME=Transform
export KB_TOP=/kb/deployment
export KB_RUNTIME=/kb/runtime

export KB_SERVICE_DIR=$KB_TOP/services/$KB_SERVICE_NAME
export KB_DEPLOYMENT_CONFIG=$KB_TOP/deployment.cfg

export PYTHONPATH=$KB_TOP/lib:$PYTHONPATH
export PATH=$KB_TOP/bin:$KB_RUNTIME/bin:$PATH
export PERL5LIB=$KB_TOP/lib:$KB_TOP/lib/perl5

pid_file=$KB_SERVICE_DIR/service.pid
wsgi_file=$KB_TOP/lib/biokbase/$KB_SERVICE_NAME/Server.py

uwsgi --master --processes 20 --cheaper 4 \
    --http :7778 --http-timeout 600 --pidfile $pid_file  \
    --wsgi-file $wsgi_file
