############################################################
#
# Autogenerated by the KBase type compiler -
# any changes made here will be overwritten
#
############################################################

try:
    import json as _json
except ImportError:
    import sys
    sys.path.append('simplejson-2.3.3')
    import simplejson as _json

import requests as _requests
import urlparse as _urlparse
import random as _random
import base64 as _base64
from ConfigParser import ConfigParser as _ConfigParser
import os as _os

_CT = 'content-type'
_AJ = 'application/json'
_URL_SCHEME = frozenset(['http', 'https'])


def _get_token(user_id, password,
               auth_svc='https://nexus.api.globusonline.org/goauth/token?' +
                        'grant_type=client_credentials'):
    # This is bandaid helper function until we get a full
    # KBase python auth client released
    auth = _base64.encodestring(user_id + ':' + password)
    headers = {'Authorization': 'Basic ' + auth}
    ret = _requests.get(auth_svc, headers=headers, allow_redirects=True)
    status = ret.status_code
    if status >= 200 and status <= 299:
        tok = _json.loads(ret.text)
    elif status == 403:
        raise Exception('Authentication failed: Bad user_id/password ' +
                        'combination for user %s' % (user_id))
    else:
        raise Exception(ret.text)
    return tok['access_token']


def _read_rcfile(file=_os.environ['HOME'] + '/.authrc'):  # @ReservedAssignment
    # Another bandaid to read in the ~/.authrc file if one is present
    authdata = None
    if _os.path.exists(file):
        try:
            with open(file) as authrc:
                rawdata = _json.load(authrc)
                # strip down whatever we read to only what is legit
                authdata = {x: rawdata.get(x) for x in (
                    'user_id', 'token', 'client_secret', 'keyfile',
                    'keyfile_passphrase', 'password')}
        except Exception, e:
            print "Error while reading authrc file %s: %s" % (file, e)
    return authdata


def _read_inifile(file=_os.environ.get(  # @ReservedAssignment
                  'KB_DEPLOYMENT_CONFIG', _os.environ['HOME'] +
                  '/.kbase_config')):
    # Another bandaid to read in the ~/.kbase_config file if one is present
    authdata = None
    if _os.path.exists(file):
        try:
            config = _ConfigParser()
            config.read(file)
            # strip down whatever we read to only what is legit
            authdata = {x: config.get('authentication', x)
                        if config.has_option('authentication', x)
                        else None for x in ('user_id', 'token',
                                            'client_secret', 'keyfile',
                                            'keyfile_passphrase', 'password')}
        except Exception, e:
            print "Error while reading INI file %s: %s" % (file, e)
    return authdata


class ServerError(Exception):

    def __init__(self, name, code, message, data=None, error=None):
        self.name = name
        self.code = code
        self.message = '' if message is None else message
        self.data = data or error or ''
        # data = JSON RPC 2.0, error = 1.1

    def __str__(self):
        return self.name + ': ' + str(self.code) + '. ' + self.message + \
            '\n' + self.data


class _JSONObjectEncoder(_json.JSONEncoder):

    def default(self, obj):
        if isinstance(obj, set):
            return list(obj)
        if isinstance(obj, frozenset):
            return list(obj)
        return _json.JSONEncoder.default(self, obj)


class KBaseExpression(object):

    def __init__(self, url=None, timeout=30 * 60, user_id=None,
                 password=None, token=None, ignore_authrc=False,
                 trust_all_ssl_certificates=False):
        if url is None:
            raise ValueError('A url is required')
        scheme, _, _, _, _, _ = _urlparse.urlparse(url)
        if scheme not in _URL_SCHEME:
            raise ValueError(url + " isn't a valid http url")
        self.url = url
        self.timeout = int(timeout)
        self._headers = dict()
        self.trust_all_ssl_certificates = trust_all_ssl_certificates
        # token overrides user_id and password
        if token is not None:
            self._headers['AUTHORIZATION'] = token
        elif user_id is not None and password is not None:
            self._headers['AUTHORIZATION'] = _get_token(user_id, password)
        elif 'KB_AUTH_TOKEN' in _os.environ:
            self._headers['AUTHORIZATION'] = _os.environ.get('KB_AUTH_TOKEN')
        elif not ignore_authrc:
            authdata = _read_inifile()
            if authdata is None:
                authdata = _read_rcfile()
            if authdata is not None:
                if authdata.get('token') is not None:
                    self._headers['AUTHORIZATION'] = authdata['token']
                elif(authdata.get('user_id') is not None
                     and authdata.get('password') is not None):
                    self._headers['AUTHORIZATION'] = _get_token(
                        authdata['user_id'], authdata['password'])
        if self.timeout < 1:
            raise ValueError('Timeout value must be at least 1 second')

    def _call(self, method, params):
        arg_hash = {'method': method,
                    'params': params,
                    'version': '1.1',
                    'id': str(_random.random())[2:]
                    }

        body = _json.dumps(arg_hash, cls=_JSONObjectEncoder)
        ret = _requests.post(self.url, data=body, headers=self._headers,
                             timeout=self.timeout,
                             verify=not self.trust_all_ssl_certificates)
        if ret.status_code == _requests.codes.server_error:
            if _CT in ret.headers and ret.headers[_CT] == _AJ:
                err = _json.loads(ret.text)
                if 'error' in err:
                    raise ServerError(**err['error'])
                else:
                    raise ServerError('Unknown', 0, ret.text)
            else:
                raise ServerError('Unknown', 0, ret.text)
        if ret.status_code != _requests.codes.OK:
            ret.raise_for_status()
        resp = _json.loads(ret.text)
        if 'result' not in resp:
            raise ServerError('Unknown', 0, 'An unknown server error occurred')
        return resp['result']

    def get_expression_samples_data(self, sample_ids):
        resp = self._call('KBaseExpression.get_expression_samples_data',
                          [sample_ids])
        return resp[0]

    def get_expression_data_by_samples_and_features(self, sample_ids, feature_ids, numerical_interpretation):
        resp = self._call('KBaseExpression.get_expression_data_by_samples_and_features',
                          [sample_ids, feature_ids, numerical_interpretation])
        return resp[0]

    def get_expression_samples_data_by_series_ids(self, series_ids):
        resp = self._call('KBaseExpression.get_expression_samples_data_by_series_ids',
                          [series_ids])
        return resp[0]

    def get_expression_sample_ids_by_series_ids(self, series_ids):
        resp = self._call('KBaseExpression.get_expression_sample_ids_by_series_ids',
                          [series_ids])
        return resp[0]

    def get_expression_samples_data_by_experimental_unit_ids(self, experimental_unit_ids):
        resp = self._call('KBaseExpression.get_expression_samples_data_by_experimental_unit_ids',
                          [experimental_unit_ids])
        return resp[0]

    def get_expression_sample_ids_by_experimental_unit_ids(self, experimental_unit_ids):
        resp = self._call('KBaseExpression.get_expression_sample_ids_by_experimental_unit_ids',
                          [experimental_unit_ids])
        return resp[0]

    def get_expression_samples_data_by_experiment_meta_ids(self, experiment_meta_ids):
        resp = self._call('KBaseExpression.get_expression_samples_data_by_experiment_meta_ids',
                          [experiment_meta_ids])
        return resp[0]

    def get_expression_sample_ids_by_experiment_meta_ids(self, experiment_meta_ids):
        resp = self._call('KBaseExpression.get_expression_sample_ids_by_experiment_meta_ids',
                          [experiment_meta_ids])
        return resp[0]

    def get_expression_samples_data_by_strain_ids(self, strain_ids, sample_type):
        resp = self._call('KBaseExpression.get_expression_samples_data_by_strain_ids',
                          [strain_ids, sample_type])
        return resp[0]

    def get_expression_sample_ids_by_strain_ids(self, strain_ids, sample_type):
        resp = self._call('KBaseExpression.get_expression_sample_ids_by_strain_ids',
                          [strain_ids, sample_type])
        return resp[0]

    def get_expression_samples_data_by_genome_ids(self, genome_ids, sample_type, wild_type_only):
        resp = self._call('KBaseExpression.get_expression_samples_data_by_genome_ids',
                          [genome_ids, sample_type, wild_type_only])
        return resp[0]

    def get_expression_sample_ids_by_genome_ids(self, genome_ids, sample_type, wild_type_only):
        resp = self._call('KBaseExpression.get_expression_sample_ids_by_genome_ids',
                          [genome_ids, sample_type, wild_type_only])
        return resp[0]

    def get_expression_samples_data_by_ontology_ids(self, ontology_ids, and_or, genome_id, sample_type, wild_type_only):
        resp = self._call('KBaseExpression.get_expression_samples_data_by_ontology_ids',
                          [ontology_ids, and_or, genome_id, sample_type, wild_type_only])
        return resp[0]

    def get_expression_sample_ids_by_ontology_ids(self, ontology_ids, and_or, genome_id, sample_type, wild_type_only):
        resp = self._call('KBaseExpression.get_expression_sample_ids_by_ontology_ids',
                          [ontology_ids, and_or, genome_id, sample_type, wild_type_only])
        return resp[0]

    def get_expression_data_by_feature_ids(self, feature_ids, sample_type, wild_type_only):
        resp = self._call('KBaseExpression.get_expression_data_by_feature_ids',
                          [feature_ids, sample_type, wild_type_only])
        return resp[0]

    def compare_samples(self, numerators_data_mapping, denominators_data_mapping):
        resp = self._call('KBaseExpression.compare_samples',
                          [numerators_data_mapping, denominators_data_mapping])
        return resp[0]

    def compare_samples_vs_default_controls(self, numerator_sample_ids):
        resp = self._call('KBaseExpression.compare_samples_vs_default_controls',
                          [numerator_sample_ids])
        return resp[0]

    def compare_samples_vs_the_average(self, numerator_sample_ids, denominator_sample_ids):
        resp = self._call('KBaseExpression.compare_samples_vs_the_average',
                          [numerator_sample_ids, denominator_sample_ids])
        return resp[0]

    def get_on_off_calls(self, sample_comparison_mapping, off_threshold, on_threshold):
        resp = self._call('KBaseExpression.get_on_off_calls',
                          [sample_comparison_mapping, off_threshold, on_threshold])
        return resp[0]

    def get_top_changers(self, sample_comparison_mapping, direction, count):
        resp = self._call('KBaseExpression.get_top_changers',
                          [sample_comparison_mapping, direction, count])
        return resp[0]

    def get_expression_samples_titles(self, sample_ids):
        resp = self._call('KBaseExpression.get_expression_samples_titles',
                          [sample_ids])
        return resp[0]

    def get_expression_samples_descriptions(self, sample_ids):
        resp = self._call('KBaseExpression.get_expression_samples_descriptions',
                          [sample_ids])
        return resp[0]

    def get_expression_samples_molecules(self, sample_ids):
        resp = self._call('KBaseExpression.get_expression_samples_molecules',
                          [sample_ids])
        return resp[0]

    def get_expression_samples_types(self, sample_ids):
        resp = self._call('KBaseExpression.get_expression_samples_types',
                          [sample_ids])
        return resp[0]

    def get_expression_samples_external_source_ids(self, sample_ids):
        resp = self._call('KBaseExpression.get_expression_samples_external_source_ids',
                          [sample_ids])
        return resp[0]

    def get_expression_samples_original_log2_medians(self, sample_ids):
        resp = self._call('KBaseExpression.get_expression_samples_original_log2_medians',
                          [sample_ids])
        return resp[0]

    def get_expression_series_titles(self, series_ids):
        resp = self._call('KBaseExpression.get_expression_series_titles',
                          [series_ids])
        return resp[0]

    def get_expression_series_summaries(self, series_ids):
        resp = self._call('KBaseExpression.get_expression_series_summaries',
                          [series_ids])
        return resp[0]

    def get_expression_series_designs(self, series_ids):
        resp = self._call('KBaseExpression.get_expression_series_designs',
                          [series_ids])
        return resp[0]

    def get_expression_series_external_source_ids(self, series_ids):
        resp = self._call('KBaseExpression.get_expression_series_external_source_ids',
                          [series_ids])
        return resp[0]

    def get_expression_sample_ids_by_sample_external_source_ids(self, external_source_ids):
        resp = self._call('KBaseExpression.get_expression_sample_ids_by_sample_external_source_ids',
                          [external_source_ids])
        return resp[0]

    def get_expression_sample_ids_by_platform_external_source_ids(self, external_source_ids):
        resp = self._call('KBaseExpression.get_expression_sample_ids_by_platform_external_source_ids',
                          [external_source_ids])
        return resp[0]

    def get_expression_series_ids_by_series_external_source_ids(self, external_source_ids):
        resp = self._call('KBaseExpression.get_expression_series_ids_by_series_external_source_ids',
                          [external_source_ids])
        return resp[0]

    def get_GEO_GSE(self, gse_input_id):
        resp = self._call('KBaseExpression.get_GEO_GSE',
                          [gse_input_id])
        return resp[0]

    def get_expression_float_data_table_by_samples_and_features(self, sample_ids, feature_ids, numerical_interpretation):
        resp = self._call('KBaseExpression.get_expression_float_data_table_by_samples_and_features',
                          [sample_ids, feature_ids, numerical_interpretation])
        return resp[0]

    def get_expression_float_data_table_by_genome(self, genome_id, numerical_interpretation):
        resp = self._call('KBaseExpression.get_expression_float_data_table_by_genome',
                          [genome_id, numerical_interpretation])
        return resp[0]
